#!/bin/bash
cd ${0%/*} || exit 1
. $WM_PROJECT_DIR/bin/tools/RunFunctions

echo "=== Channel flow Re_tau=5200 ==="

echo "--- Running standard kOmega ---"
( cd kOmega && runApplication blockMesh && runApplication simpleFoam )

echo "--- Running kOmegaDavidsonNN ---"
( cd kOmegaDavidsonNN && runApplication blockMesh && runApplication simpleFoam )

echo "--- Post-processing ---"
python3 ../../postProcessing/plotChannelFlow.py kOmegaDavidsonNN kOmega
python3 ../../postProcessing/plotSigmaK_pySR_vs_NN.py kOmegaDavidsonNN

echo "=== Channel flow complete ==="
