#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

canCompile || exit 0    # Dynamic code

restore0Dir

runApplication blockMesh

runApplication topoSet

# 1-cell-thick (empty front/back) 2D approximation -- ~32k cells, runs
# serially in a couple of minutes, no decomposition needed.
runApplication $(getApplication)

#------------------------------------------------------------------------------
